baseURL = 'https://xsliulab.github.io/CancerBiology'
relativeURLs = false
languageCode = 'en-us'
title = 'Cancer Biology'
theme = 'hugo-theme-relearn'

[params]
  additionalContentLanguage = ['en']
  alwaysopen = ''
  breadcrumbSeparator = '>'
  collapsibleMenu = false
  customMathJaxURL = ''
  customMermaidURL = ''
  customOpenapiURL = ''
  disableAssetsBusting = false
  disableBreadcrumb = false
  disableExplicitIndexURLs = false
  disableGeneratorVersion = false
  disableHoverBlockCopyToClipBoard = false
  disableInlineCopyToClipBoard = true
  disableLandingPageButton = true
  #语言转换
  disableLanguageSwitchingButton = true
  disableMathJax = true
  disableMermaid = true
  disableNextPrev = false
  disableOpenapi = true
  disableRandomIds = false
  disableRootBreadcrumb = true
  disableSearch = false
  disableSearchHiddenPages = false
  disableSeoHiddenPages = true
  disableShortcutsTitle = false
  disableTagHiddenPages = false
  disableTermBreadcrumbs = false
  disableToc = false
  editURL = 'https://github.com/XSLiuLab/CancerBiology/tree/main/content/${FilePath}'
  externalLinkTarget = '_self'
  highlightWrap = true
  images = ['images/tn.png']
  mathJaxInitialize = '{}'
  mermaidInitialize = '{ "securityLevel": "loose" }'
  mermaidZoom = true
  ordersectionsby = 'weight'
  showVisitedLinks = true
  titleSeparator = '::'

  [params.author]
    name = 'Shanghaitech liuxslab'

  [params.image]
    errorlevel = 'error'

  [params.imageEffects]
    border = true
    lazy = true
    lightbox = true
    shadow = false

  [params.include]
    errorlevel = 'error'

  [params.link]
    errorlevel = 'error'

  [params.openapi]
    errorlevel = 'error'

  [params.social]
    facebook_admin = ''
    twitter = ''

  [[params.themeVariant]]
    auto = ['zen-light', 'zen-dark']
    identifier = 'zen-auto'
    name = 'Zen Light/Dark'

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.themeVariant]]
    identifier = 'zen-dark'


[outputs]
  home = ['html', 'rss', 'search']
  page = ['html', 'rss',]
  section = ['html', 'rss',]

[menu]
  [[menu.shortcuts]]
    identifier = 'ds'
    name = "<i class='fa-fw fab fa-github'></i> Liulab GitHub"
    url = 'https://github.com/XSLiuLab'
    weight = 10

  [[menu.shortcuts]]
    name = "<i class='fa-fw fa fa-bank'></i> Shanghaitech"
    url = 'https://www.shanghaitech.edu.cn/'
    weight = 11



  [[menu.shortcuts]]
    identifier = 'cancerquest'
    name = "<i class='fa-fw fa fa-chain'></i> CanceQquest"
    url = 'https://cancerquest.org/cancer-biology'
    weight = 20

  [[menu.shortcuts]]
    identifier = '肿瘤生物学概论'
    name = "<i class='fa-fw fa fa-chain'></i> 肿瘤生物学概论"
    url = 'https://www.xuetangx.com/course/THU08261001403/4227257?channel=search_result'
    weight = 25

  [[menu.shortcuts]]
    identifier = 'hugodoc'
    name = "<i class='fa-fw fas fa-bookmark'></i> Hugo Documentation"
    url = 'https://gohugo.io/'
    weight = 30


  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-bullhorn'></i> Credits"
    url = 'more/credits/'
    weight = 40
